version: '3.8'

services:
  my-backend:
    build: .
    container_name: my-spring-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    volumes:
       - ./logs:/app/logs